# Site settings
title: YorkYan's Blog
email: codersimple@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codersimple.github.io/" # the base hostname & protocol for your site
description: Hello World!
